### PR TITLE
fix: meta mod key on focus handling for gnome/x11

### PR DESCRIPTION
**Pull request by rti**
This patch addresses an issue in the modifier key handling appearing on
gnome/x11 while focussing a winit window using a meta/super/logo key
shortcut.

As soon as the window gained focus via a shortcut using a meta key,
gnome/x11 reports a meta modifier as pressed in the focus event, even
though it was just released. No key release events were sent afterwards,
so the meta modifier remained "stuck" in the winit state.

This patch refactors the modifier key handling following this goals:
 - Only rely on winit's own modifier state tracking for key and focus
   events, do not mix it with x11's modifier reporting
 - Track modifiers only via non-raw key events, so winit does not track
   modifier changes when not focussed
 - Integrate modifier handling with the synthetic key events mechanism
   in order to report release of all currently held modifiers when
   unfocussed and report set for all currently held modifiers when
   focussed.

This problem appeared using Neovide. I put down some more information and a deprecated approach to fix it over at neovide https://github.com/neovide/neovide/pull/931. A similar issue has been reported by @mrotaru as well here https://github.com/neovide/neovide/issues/942.

### CODE REVIEW

**Comment by rti** [comment]
Upstream PR https://github.com/maroider/winit/pull/1

**Comment by last-partizan** [comment]
@rti this exact changed is merged upstream? so we can close PR and just sync with upstream?

@Kethku could you, please, look at this?

**Comment by rti** [comment]
@last-partizan Well, this was a back port for https://github.com/maroider/winit/pull/1. So yes, you also get the change when merging syncing with https://github.com/maroider/winit/tree/new-keyboard-linux

**Comment by last-partizan** [comment]
@rti I'm trying to reproduce bugs and test if this fix works.

Simplest way to trigger a bug:

1. Open neovide (`cargo r -- README.md`)
2. Win + Right Arrow (Move window to right part of the screen in gnome)
3. Try to do something, like moving cursor or entering edit mode - doesn't work

I changed Cargo.toml in `neovide` to use my local version of `glutin`, where i'm using your fork

(Cargo.toml from neovim)
```diff
diff --git a/Cargo.toml b/Cargo.toml
index bcd4649..50e6307 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -39,8 +39,9 @@ dirs = "2"
 rand = "0.7"
 pin-project = "0.4.27"
 futures = "0.3.12"
-glutin = { git = "https://github.com/neovide/glutin", branch = "new-keyboard-all" }
-winit = { git = "https://github.com/rti/winit", branch = "fix-gnome-x11-meta-mod-focus" }
+glutin = { path = "/home/serg/src/glutin/glutin" }^M
+# glutin = { git = "https://github.com/neovide/glutin", branch = "new-keyboard-all" }^M
+# winit = { git = "https://github.com/neovide/winit", branch = "new-keyboard-all" }^M
 gl = "0.14.0"
 swash = "0.1.4"
 clap="2.33.3"
```

(glutin/Cargo.toml)
```diff
diff --git a/glutin/Cargo.toml b/glutin/Cargo.toml
index c01cb8a..bb7a732 100644
--- a/glutin/Cargo.toml
+++ b/glutin/Cargo.toml
@@ -21,7 +21,7 @@ default = ["x11", "wayland"]

 [dependencies]
 lazy_static = "1.3"
-winit = { git = "https://github.com/Kethku/winit", branch = "new-keyboard-all", default-features = false }
+winit = { git = "https://github.com/rti/winit", branch = "fix-gnome-x11-meta-mod-focus" }

 [target.'cfg(target_os = "android")'.dependencies]
 android_glue = "0.2"
```

After i build neovim, bug still here. Am i doing something wrong, or it indeed not fixed?

**Comment by rti** [comment]
@last-partizan Unfortunately, I do not have Gnome nor Xorg available in my setup to test anymore. Sorry!

**Comment by rti** [comment]
From my point of view, I'd just close this PR.

**Comment by last-partizan** [comment]
Well, i think now it's up to me to dig up and fix this :)

I'll try to understand why it is happening and how to fix this :)

**Comment by last-partizan** [comment]
This is indeed does not fix the issue, but i found reliable way to test it:

It works only in x11, and in my gnome/wayland i'm using following
```vim
# This is my copy-paste keybindings
map <S-Insert>		"*gP
cmap <S-Insert>		<C-R>*
imap <S-Insert>		<C-R>*
vnoremap <C-Insert> "*y

map <C-S-v>		"*gP
cmap <C-S-v>		<C-R>*
imap <C-S-v>		<C-R>*
vmap <C-S-c>   "*Y
```

```bash
export WINIT_UNIX_BACKEND=x11
cargo r
```

Then, press `Shift+Insert`, it should insert text. Then press `Insert`, it it pastes text again, bug is here.

I'm continuing my investigation.

**Pull request closed without merging**
