### PR TITLE
Fix modifiers handling

### PR DESCRIPTION
**Pull request by last-partizan**
This should fix some keyboard modifier related bugs:

- https://github.com/neovide/neovide/issues/951 (Not fixed? Not sure, looks like fixed)
- https://github.com/neovide/neovide/issues/1142 (Fixed)
- https://github.com/neovide/neovide/issues/942

For some reason there was two states for tracking modifiers, after removing one, i haven't encountered any problems during the day of normal coding.

### CODE REVIEW

**Comment by last-partizan** [comment]
@Kethku @LoipesMas @clason please take a look at this.

I've used this branch for a 4 days, and it works fine for me.

This change affects only Linux/X11 users, and i plan to merge it tomorrow, if everything is looking good.

**Comment by LoipesMas** [comment]
I don't remember having any issues with modifier keys (even though I'm on X11), so I can't confirm whether this fixes thing.
But how does it look upstream? Is it fixed there or should this change probably be also applied there?

**Comment by last-partizan** [comment]
Upstream winit still doesn't merged code which we are using, and which have this bug.

If i remember correctly, we're merged some of this: https://github.com/maroider/winit/tree/new-keyboard-linux

And there bug was already fixed, but in more obscure way: https://github.com/maroider/winit/pull/1
So, i reverted it there, and created PR with this fix: https://github.com/maroider/winit/pull/8

**Comment by LoipesMas** [comment]
I see.
I think we can merge this then.
Hopefully in not-too-far future those change will be merged upstream so we don't have to manage our own fork.

**Comment by last-partizan** [comment]
Hmm, i found one bug in my implementation, my code does not distinguish between left and right shift, and when we press both, and release one - it will think that both are released.

Probably, there was a reason to store keycodes here.

**Comment by last-partizan** [comment]
I'm closing this, and instead make PR in neovide to use new branches.

**Pull request closed without merging**
